//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCopies.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCopies.Util.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrays must have only one dimension..
        /// </summary>
        public static string ArrayWithMoreThanOneDimension {
            get {
                return ResourceManager.GetString("ArrayWithMoreThanOneDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current object or value is disposing..
        /// </summary>
        public static string CurrentObjectIsDisposing {
            get {
                return ResourceManager.GetString("CurrentObjectIsDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The declaring types of &apos;{0}&apos; and &apos;{1}&apos; do not correspond. The declaring types of &apos;{0}&apos; and &apos;{1}&apos; must correspond for read-only properties when an integrity check is performed..
        /// </summary>
        public static string DeclaringTypesNotCorrespond {
            get {
                return ResourceManager.GetString("DeclaringTypesNotCorrespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; couldn&apos;t be found in &apos;{1}&apos;..
        /// </summary>
        public static string FieldOrPropertyNotFound {
            get {
                return ResourceManager.GetString("FieldOrPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enum value is not in the enum values range. The enum value is {0}..
        /// </summary>
        public static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given enum does not have the FlagsAttribute attribute..
        /// </summary>
        public static string NonFlagsEnumException {
            get {
                return ResourceManager.GetString("NonFlagsEnumException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given enum type does not have the FlagsAttribute attribute..
        /// </summary>
        public static string NonFlagsEnumTypeException {
            get {
                return ResourceManager.GetString("NonFlagsEnumTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be one of the {1} enum values..
        /// </summary>
        public static string NoValidEnumValue {
            get {
                return ResourceManager.GetString("NoValidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has one or more same key..
        /// </summary>
        public static string OneOrMoreSameKey {
            get {
                return ResourceManager.GetString("OneOrMoreSameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not an expected value..
        /// </summary>
        public static string ParameterIsNotAnExpectedValue {
            get {
                return ResourceManager.GetString("ParameterIsNotAnExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection is read-only..
        /// </summary>
        public static string ReadOnlyCollection {
            get {
                return ResourceManager.GetString("ReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is empty or white spaces..
        /// </summary>
        public static string StringParameterEmptyOrWhiteSpaces {
            get {
                return ResourceManager.GetString("StringParameterEmptyOrWhiteSpaces", resourceCulture);
            }
        }
    }
}
