//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCopies.Util.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCopies.Util.Desktop.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BackgroundWorker does not support cancellation..
        /// </summary>
        public static string BackgroundWorkerDoesNotSupportCancellation {
            get {
                return ResourceManager.GetString("BackgroundWorkerDoesNotSupportCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BackgroundWorker does not support pausing..
        /// </summary>
        public static string BackgroundWorkerDoesNotSupportPausing {
            get {
                return ResourceManager.GetString("BackgroundWorkerDoesNotSupportPausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BackgroundWorker does not support progression notification..
        /// </summary>
        public static string BackgroundWorkerDoesNotSupportProgressionNotification {
            get {
                return ResourceManager.GetString("BackgroundWorkerDoesNotSupportProgressionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BackgroundWorker is busy..
        /// </summary>
        public static string BackgroundWorkerIsBusy {
            get {
                return ResourceManager.GetString("BackgroundWorkerIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comparison result value returned by the comparison method of the given parameter is not supported..
        /// </summary>
        public static string ComparisonResultReturnedByParameterIsNotSupported {
            get {
                return ResourceManager.GetString("ComparisonResultReturnedByParameterIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion did not succeeded..
        /// </summary>
        public static string ConversionDidNotSucceeded {
            get {
                return ResourceManager.GetString("ConversionDidNotSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} conversion direction is not supported..
        /// </summary>
        public static string ConversionDirectionNotSupported {
            get {
                return ResourceManager.GetString("ConversionDirectionNotSupported", resourceCulture);
            }
        }
    }
}
